SELECT TOP (1000) [Sr.no]
      ,[name]
      ,[year]
      ,[movie_rated]
      ,[run_length]
      ,[genres]
      ,[release_date]
      ,[IMDB_rating]
      ,[num_raters]
      ,[num_reviews]
      ,[review_url]
      ,[image_Url]
      ,[rating]
      ,[keyword]
      ,[review_date]
      ,[review]
      ,[sentiments]
  FROM [dbo].[Azure Blob Storage file]